using System;
namespace TestCoreWebAPI.Models
{
	public class AssignmentDetailsItem
	{
		public string PrjLocCode { get; set; }          //LabLocation
		public int PrjCode { get; set; }
		public string PrjType { get; set; }
		public string PrjStatus { get; set; }
		public int? PrjOrgProgrm { get; set; }
		public int? PrjOrgQuote { get; set; }
		public string PrjLdesc { get; set; }
		public string PrjSdesc { get; set; }
		public string PrjDefaultPo { get; set; }
		public string PrjDefaultWo { get; set; }
		public DateTime? PrjQuoteStart { get; set; }
		public DateTime? PrjQuoteExpire { get; set; }
		public DateTime? PrjStartDate { get; set; }
		public string SclCode { get; set; }
		public int? PrjDisposalDays { get; set; }
		public string PrjCatLoc { get; set; }
		public Guid? PrjCatId { get; set; }
		public Guid? PrjTaCode { get; set; }
		public string TmplBoLocCode { get; set; }
		public int? TmplBoCode { get; set; }
		public string TmplCocLocCode { get; set; }
		public int? TmplCocNum { get; set; }
		public Guid? FormatId { get; set; }
		public string JdeCusCode { get; set; }
		public byte? PrjForceIcoc { get; set; }
		public int? RecStatId { get; set; }
		public DateTime? AuditDatetime { get; set; }
		public Guid? AuditUserId { get; set; }
		public string AuditReason { get; set; }
		public string AuditApplication { get; set; }
		public Guid Guid { get; set; }
		public int? PrjOrgProject { get; set; }
		public Guid? ModId { get; set; }
		public string JdeTermCode { get; set; }
		public int? PrjGsa { get; set; }
		public byte? PrjVtsr { get; set; }
		public Guid? PrjManager { get; set; }
		public Guid? PrjQuoteCreator { get; set; }
		public Guid? ContractId { get; set; }
		public Guid? TctId { get; set; }
		public decimal? PrjTaMulti { get; set; }
		public Guid? FlagSuiteId { get; set; }
		public int? PrjDataRetainYrs { get; set; }
		public string PrjWorkOrigin { get; set; }
		public byte? PrjForceSiteValid { get; set; }
		public Guid? PrjMgrAssistant { get; set; }
		public byte? PrjHouseAcct { get; set; }
		public Guid? PrjAccountExec { get; set; }
		public byte? PrjDryCorr { get; set; }
		public byte? AuditAuthenticated { get; set; }
		public string PrjReportFooter { get; set; }
		public string PrjInvAttn { get; set; }
		public byte? PrjMethodsOnly { get; set; }
		public byte? PrjRptBothLmt { get; set; }
		public decimal? PrjMinInvoice { get; set; }
		public Guid? PrjDiscntMgmUsrId { get; set; }
		public Guid? PrjDiscntApproveUsrId { get; set; }
		public string PrjDiscntApproveComment { get; set; }
		public DateTime? PrjDiscntApproveDateTime { get; set; }
		public Guid? MsId { get; set; }
		public DateTime? PrjQuoteDue { get; set; }
		public DateTime? PrjEndDue { get; set; }
		public string PrjWinProbability { get; set; }
		public byte? PrjContractualTerms { get; set; }
		public Guid? BsId { get; set; }
		public Guid? WlrId { get; set; }
		public string PrjWonLossComment { get; set; }
		public Guid? LcId { get; set; }
		public string PrjApprovalJust { get; set; }
		public byte? PrjAllowCopyLogin { get; set; }
		public byte? PrjUseMSubListDesc { get; set; }
		public byte? PrjQaqcOnly { get; set; }
		public string PrjNcmMergeOp { get; set; }
		public Guid? AltFormatId { get; set; }
		public string PrjStateCode { get; set; }
		public decimal? PrjQuoteDollars { get; set; }
		public string RlsCode { get; set; }
		public byte? PrjPriceQc { get; set; }
		public Guid? TerFormatId { get; set; }
		public Guid? PrjPgmManager { get; set; }
		public int? PrjTotalaccessView { get; set; }
		public int? PrjInvoiceFormat { get; set; }
		public byte? PrjCertNotRequired { get; set; }
		public byte? PrjAutoPostCoc { get; set; }
		public byte? PrjAutoPostLoginConf { get; set; }
		public byte? PrjAutoMergeInvoiceCoc { get; set; }
		public byte? PrjAutoPostReport { get; set; }
		public byte? PrjAutoPostEdd { get; set; }
		public Guid? PrjQuoteAeOwner { get; set; }
		public Guid? QcpId { get; set; }
		public DateTime? PrjOriginalApproveDate { get; set; }
		public DateTime? PrjWonLossDate { get; set; }
		public Guid? PrjIndustrySegment { get; set; }
		public Guid? PrjMarketSegment { get; set; }
		public string PrjReportWatermark { get; set; }
		public DateTime? ProjectDateAdded { get; set; }
		public byte? PrjWonLossDateSynth { get; set; }
		public byte? PrjUnderLegalReview { get; set; }
		public byte? PrjAskBeforeDestory { get; set; }
		public int? DrtId { get; set; }
		public int? PrjTzId { get; set; }
		public byte? PrjAskBeforeDestroy { get; set; }
		public byte? PrjMultiYearOpportunity { get; set; }
		public decimal? PrjEstimatedOpportunity { get; set; }
		public decimal? PrjTotalAmount { get; set; }
		public decimal? PrjReferenceTotalAmount { get; set; }

	}
}
